In [ ]:
Darjeeling = [73, 68, 42]

In [12]:
#2d array
import numpy as np
a=np.array([[
            [1,2,1],
            [1,2,1],
            [2,2,1]
            ],
            [
            [2,2,1],
            [3,3,1],
            [2,2,1]
            ]
            ])
b=np.array([[
            [2,2,1],
            [2,2,3],
            [4,2,1]
            ],
            [
            [5,2,1],
            [2,3,3],
            [1,2,4]
            ]
            ])

In [13]:
#3d array
import numpy as np
print(a.shape)
print(a.dtype)

print(np.dot(a,b))

(2, 3, 3)
int32
[[[[10  8  8]
   [10 10 11]]

  [[10  8  8]
   [10 10 11]]

  [[12 10  9]
   [15 12 12]]]


 [[[12 10  9]
   [15 12 12]]

  [[16 14 13]
   [22 17 16]]

  [[12 10  9]
   [15 12 12]]]]


In [14]:
np.matmul(a,b)

array([[[10,  8,  8],
        [10,  8,  8],
        [12, 10,  9]],

       [[15, 12, 12],
        [22, 17, 16],
        [15, 12, 12]]])

In [16]:
a@b

array([[[10,  8,  8],
        [10,  8,  8],
        [12, 10,  9]],

       [[15, 12, 12],
        [22, 17, 16],
        [15, 12, 12]]])