<h1>8 queen problem<h1>

In [38]:
import numpy

canvas=numpy.ndarray(shape=(8,8), dtype=int)
#print(canvas)

In [75]:
#reset
def reset():
    for i in range(len(canvas)):
        canvas[i]=0
    #print(canvas)
reset()
#print(canvas)

In [78]:
def put(l,k):
    for i in range(len(canvas)):
        for j in range(len(canvas)):
            #horizontal line
            canvas[l,j]=-1
            #vertical line
            canvas[i,k]=-1
            
            #diagonals
            if l+j<8 and k+j<8 :
                #print(j)
                canvas[l+j,k+j]=-1
                canvas[l-j,k+j]=-1
                
            if l-j>-1 and k-j>-1:
                canvas[l-j,k-j]=-1
                canvas[l+j,k-j]=-1
                
            #placing the queen
            canvas[l,k]=1            

    #print(canvas)

In [84]:
b=0
g=0
def queen(b):
    #put(0,b)
    g=0
    if(g!=8):
        for i in range(len(canvas)):
            for j in range(len(canvas)):  
                if canvas[i,j]!=-1:
                    put(i,j)
                    #print(canvas)
                    g+=1
    if(g!=8):
        #print(g)
        reset()
        if b<7:
            print(b,g)
            queen(b+1)
    else:
        print("hey")
        print(g)
        print(canvas)
        return
                
queen(b)
#print(canvas)      

0 5
1 5
2 5
3 5
4 5
5 5
6 5


In [81]:
 print(canvas)

[[ 0  0  0 -1  0  0  0  0]
 [-1  0  0 -1  0  0 -1  0]
 [ 0 -1  0 -1  0 -1  0  0]
 [ 0  0 -1 -1 -1  0  0  0]
 [-1 -1 -1  1 -1 -1 -1 -1]
 [ 0  0 -1 -1 -1  0  0  0]
 [ 0 -1  0 -1  0 -1  0  0]
 [-1  0  0 -1  0  0 -1  0]]


In [80]:
put(4,3)