In [1]:
import numpy

canvas=numpy.ndarray(shape=(7,5), dtype=int)
print(canvas)

[[4128860 6029375 3801155 5570652 6619251]
 [7536754 4456540 4980805 6029388 7209057]
 [6488161 7209071 6357092 6029363 6881388]
 [6029410 6881395 6619252 7340077 6488161]
 [6357099 6619239 6029427 7667822 7340141]
 [6029433 7340127 7602297 7536741 7602292]
 [7536741 6619252 3014770 7929968 7929856]]


In [2]:
#reset
for i in range(len(canvas)):
    canvas[i]=0
print(canvas)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [3]:
print(canvas)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [4]:
#vertical line
def horizontal(r):
    for i in r:
        canvas[i]=1
        canvas[i,0]=canvas[i,4]=0
    #print(canvas)

In [5]:
def vertical(c,h):
    if h==1:
        for i in range(1,4):
            canvas[i,c]=1
    elif h==-1:
        for i in range(3,6):
            canvas[i,c]=1
    elif h==0:
        for i in range(1,6):
            canvas[i,c]=1
    
    #print(canvas)
vertical(1,-1)

In [6]:
#TWO
h=[1,3,5] 
v=[3,1,1,-1]

def draw(h,v):
    horizontal(h)
    j=0
    for i in range(3):
        if j>len(v):
            vertical(v[j],v[j+1])
            j+=2
    print(canvas)
draw(h,v)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
