In [3]:
import numpy as np
x = np.array([1,3,4,5,6,7,2])
print(x<3)         #normal method

#numpy method
print(np.less(x,3))
print(np.greater(x,3))
print(np.less_equal(x,3))
print(np.greater_equal(x,3))
print(np.equal(x,3))
print(np.not_equal(x,3))

[ True False False False False False  True]
[ True False False False False False  True]
[False False  True  True  True  True False]
[ True  True False False False False  True]
[False  True  True  True  True  True False]
[False  True False False False False False]
[ True False  True  True  True  True  True]


In [13]:
#counting entries
x = np.random.randint(10, size=(100,100))
print(x)

[[0 4 0 ... 9 3 9]
 [2 9 0 ... 2 4 1]
 [7 8 7 ... 6 3 7]
 ...
 [8 4 6 ... 3 5 2]
 [8 1 9 ... 2 1 6]
 [6 6 2 ... 6 1 0]]


In [6]:
np.count_nonzero(x==6)#same

1026

In [7]:
np.sum(x==6)#sameb

1026

In [10]:
l1=[1,2,3,4,5]
print(l1[l1>2])

TypeError: '>' not supported between instances of 'list' and 'int'

In [ ]:
print(x[x>5])
print("rainy day more than avg rainfall",inches[inches>np.mean(inches)])

In [11]:
import pandas as pd
# use pandas to extract rainfall inches as a NumPy array
rainfall = pd.read_csv('seattle2014.csv')
#print(rainfall)
A=np.array(rainfall['PRCP'])
#print(rainfall)
inches = A / 254.0  # 1/10mm -> inches #254mm = 10.0in
# print(rainfall)
print(inches)
# print(inches.mean())

[0.         0.16141732 0.05905512 0.         0.         0.01181102
 0.48031496 0.38188976 0.22834646 0.16929134 0.83858268 0.05905512
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.01968504 0.         0.
 0.         0.         0.         0.3503937  0.8503937  0.
 0.09055118 0.07874016 0.         0.         0.         0.
 0.         0.         0.2007874  0.01968504 0.72047244 0.66929134
 0.18110236 0.07086614 0.37007874 0.46062992 1.03937008 0.57086614
 0.5984252  0.03937008 0.11811024 0.11023622 0.0984252  0.24015748
 0.51181102 0.01181102 0.         0.         0.         0.01968504
 0.7519685  0.42125984 0.6496063  1.83858268 0.11811024 0.
 1.27165354 0.16929134 0.74015748 0.         0.         0.01968504
 0.27165354 0.31889764 1.09055118 0.01181102 0.         0.01968504
 0.         0.         0.         0.         0.         0.16141732
 0.14173228 0.01181102 0.87007874 0.5511811  0.         0.
 0.         0.         0.0984252  0.       

In [11]:
print("No. of days with more than mean rain: ", np.sum(inches>inches.mean()))

No. of days with more than mean rain:  93


In [17]:
ind = [3, 7, 2]
print(x[ind])

[[5 2 5 6 9 4 6 1 2 7 0 1 7 5 3 1 9 7 1 4 9 5 2 9 4 6 6 0 3 9 7 4 2 3 3 6
  0 7 6 2 1 1 4 5 1 9 8 7 0 8 8 9 8 9 7 8 2 4 3 8 9 2 1 2 3 4 3 4 2 6 6 0
  2 0 2 0 2 4 1 9 8 5 9 1 5 7 1 3 9 0 3 9 2 0 3 1 5 0 6 1]
 [3 4 8 5 1 3 1 8 8 2 5 6 6 3 4 3 4 5 7 9 7 4 2 1 4 4 9 5 8 6 3 6 5 4 8 5
  9 9 0 4 2 6 3 1 4 5 8 9 4 0 3 2 6 6 6 1 3 4 7 6 7 4 7 8 5 3 7 8 8 4 7 9
  4 8 7 3 3 1 0 4 8 9 2 0 2 5 4 7 0 3 2 5 2 2 8 6 4 3 2 5]
 [7 8 7 3 2 4 0 4 2 0 9 0 1 7 9 1 8 1 5 7 8 0 0 6 5 5 8 3 6 4 6 9 4 3 8 2
  7 9 0 4 6 5 9 6 3 3 3 2 7 6 5 7 6 4 3 1 1 9 2 8 2 2 8 4 3 5 5 7 2 3 7 8
  5 3 0 8 7 1 1 7 7 6 1 7 6 2 1 3 4 2 6 7 1 4 5 7 3 6 3 7]]


In [21]:
x = ([2,4,2,6,])
a = (np.sort(x))
b = a[::-1]
c = np.argsort(x) 
print(a,b)
print(c)

[2 2 4 6] [6 4 2 2]
[0 2 1 3]


In [22]:
np.sort(x, axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1