In [3]:
import numpy as np


In [5]:
#integer array
a=[1,2,3,4,5,6]
np.array(a)
print(a)#list
print(np.array(a))#array

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [9]:

print(np.array([1,2,3,4,5,6,7.64], dtype=int))



[1 2 3 4 5 6 7]


In [8]:
print(np.zeros(10,dtype=int))

[0 0 0 0 0 0 0 0 0 0]


In [10]:
print(np.ones(10,dtype=int))

[1 1 1 1 1 1 1 1 1 1]


In [11]:
print(np.full((3,5),4.8))#3x5 array filled with value 4.8

[[4.8 4.8 4.8 4.8 4.8]
 [4.8 4.8 4.8 4.8 4.8]
 [4.8 4.8 4.8 4.8 4.8]]


In [12]:
#linear sequence
print(np.arange(0,20,2))

[ 0  2  4  6  8 10 12 14 16 18]


In [13]:
#linear spacing
b=np.linspace(0,10,100)#100 values from 10 t0 10
print(b)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [16]:
c=np.eye(5,5)#identity matrix
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
d=np.random.random((3,3))
print(d)

[[0.58408449 0.60415258 0.7889308 ]
 [0.74077568 0.04260261 0.24082298]
 [0.01565119 0.78953922 0.48745233]]


In [20]:
e=np.random.normal(5,2.8,(3,3))#mean=5, sd=2.8
print(e)

[[ 2.91181751  5.39845214 -0.89501835]
 [ 9.30672581  9.09002748  0.1972634 ]
 [ 4.02058153  8.07691151  7.09764146]]


In [ ]:
f= np.random.randint()